# (실행 환경 dev 설정)
# : 개발 환경 개발자들을 위한 환경 설정

spring:
  application:
    # Eureka 에 등록될 서비스 이름 (복제 서버는 같은 이름으로 설정하여 로드밸런싱)
    name: SAMPLE-JPA-DEV

  config:
    activate: # 프로필명 설정
      on-profile: dev

  servlet:
    multipart:
      # !!!multipart 데이터량 설정!!!
      maxFileSize: 50MB
      maxRequestSize: 50MB

springdoc:
  swagger-ui:
    enabled: true # Swagger 문서 공개 여부

# JPA DataSource 설정
datasource-jpa:
  # Database 추가
  # 작명법은, 앞에 db{index}-{제목} 형식으로 하여, datasource 별 충돌을 피하기

  # (서비스 데이터베이스)
  db1-main: # DB 추가
    # 데이터베이스 접속 경로
    # !!!serverTimezone 설정을 데이터베이스의 타임존 설정과 일치시켜주세요.!!!
    # 로컬 DB 접속은 localhost 를 사용하고, 도커에서 로컬 DB 접속시엔 host.docker.internal 를 사용하세요.
    # DB 클러스터 사용시 각 클러스터를 별도 데이터소스로 구성하면 됩니다.
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/first_schema?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    # 데이터베이스의 사용자명
    username: root
    # 데이터베이스의 패스워드
    password: todo1234!
    # 데이터베이스 접속시 사용하는 드라이버
    driverClassName: com.mysql.cj.jdbc.Driver
    data: classpath:sql/data-h2.sql
    initialization-mode: always
    database-platform: org.hibernate.dialect.MySQLDialect

custom-config: # 프로젝트 내에서 사용하는 커스텀 설정
  # cors 허용 리스트 설정 (설정하지 않으면 모든 요청 허용)
  cors-allow-list: http://localhost:8081, http://127.0.0.1:8081, http://localhost:3000, http://127.0.0.1:3000