# (실행 환경 dev 설정)
# : 개발 환경 개발자들을 위한 환경 설정

spring:
  application:
    # Eureka 에 등록될 서비스 이름 (복제 서버는 같은 이름으로 설정하여 로드밸런싱)
    name: TEMPLATE-DEV

  config:
    activate: # 프로필명 설정
      on-profile: dev

  servlet:
    multipart:
      # !!!multipart 데이터량 설정!!!
      maxFileSize: 50MB
      maxRequestSize: 50MB

springdoc:
  swagger-ui:
    enabled: true # Swagger 문서 공개 여부

custom-config: # 프로젝트 내에서 사용하는 커스텀 설정
  # cors 허용 리스트 설정 (설정하지 않으면 모든 요청 허용)
  cors-allow-list: http://localhost:8081, http://127.0.0.1:8081, http://localhost:3000, http://127.0.0.1:3000