# (실행 환경 local 설정)
# : 로컬 환경 개발자를 위한 환경 설정 = 서버 개발자가 마음껏 사용 가능 (그냥 IDE 를 실행하면 적용)

spring:
  application:
    # Eureka 에 등록될 서비스 이름 (복제 서버는 같은 이름으로 설정하여 로드밸런싱)
    name: SAMPLE-MONGODB-LOCAL

  config:
    activate: # 프로필명 설정
      on-profile: local

  servlet:
    multipart:
      # !!!multipart 데이터량 설정!!!
      maxFileSize: 50MB
      maxRequestSize: 50MB

springdoc:
  swagger-ui:
    enabled: true # Swagger 문서 공개 여부

# MongoDB DataSource 설정
datasource-mongodb:
  # MongoDB 추가
  # 작명법은, 앞에 md{index}-{제목} 형식으로 하여, datasource 별 충돌을 피하기

  # (주 사용 MongoDB)
  # mongodb:// 뒤에 인증 아이디 : 인증 비밀번호를 넣어주고, @ 뒤에는 레플리카 접속 주소를 모두 넣어주며,
  # ? 뒤의 replicaSet 은 레플리카 셋 이름을, authSource 는 사용자 정보가 저장된 데이터베이스를 설정하면 됩니다.
  mdb1-main:
    uri: mongodb://root:todo1234!@127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/db?replicaSet=rs0&authSource=admin

logging:
  level:
    org.springframework.data.mongodb: INFO # mongoDB 로깅 설정

custom-config: # 프로젝트 내에서 사용하는 커스텀 설정
  # cors 허용 리스트 설정 (설정하지 않으면 모든 요청 허용)
  cors-allow-list: http://localhost:8081, http://127.0.0.1:8081, http://localhost:3000, http://127.0.0.1:3000